// <auto-generated />
using BankingApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankingApi.Migrations
{
    [DbContext(typeof(BankingDbContext))]
    [Migration("20260328053744_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BankingApi.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Balance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 1985.40m,
                            Balance = "$12,234.45",
                            Date = "2019-12-03",
                            Description = "HACKERBANK INC. DES:CCD+ ID: 33375894749",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Amount = 42.99m,
                            Balance = "$10,249.05",
                            Date = "2019-12-02",
                            Description = "AMAZON.COM*MT1TA4IQ0 AMZN.COM/BILLWA",
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 87.34m,
                            Balance = "$10,292.04",
                            Date = "2019-12-02",
                            Description = "WHOLE FOODS MARKET #10432 SAN FRANCISCO CA",
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            Amount = 3500.00m,
                            Balance = "$10,379.38",
                            Date = "2019-12-01",
                            Description = "PAYROLL DIRECT DEPOSIT TECHCORP INC",
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            Amount = 13.99m,
                            Balance = "$6,879.38",
                            Date = "2019-11-29",
                            Description = "NETFLIX.COM LOS GATOS CA",
                            Type = 1
                        },
                        new
                        {
                            Id = 6,
                            Amount = 6.75m,
                            Balance = "$6,893.37",
                            Date = "2019-11-28",
                            Description = "STARBUCKS STORE #08765 SAN JOSE CA",
                            Type = 1
                        },
                        new
                        {
                            Id = 7,
                            Amount = 250.00m,
                            Balance = "$6,900.12",
                            Date = "2019-11-28",
                            Description = "VENMO CASHOUT DES:TRANSFER ID: 99887766",
                            Type = 0
                        },
                        new
                        {
                            Id = 8,
                            Amount = 55.20m,
                            Balance = "$6,650.12",
                            Date = "2019-11-27",
                            Description = "SHELL OIL 12345678 SAN FRANCISCO CA",
                            Type = 1
                        },
                        new
                        {
                            Id = 9,
                            Amount = 200.00m,
                            Balance = "$6,705.32",
                            Date = "2019-11-26",
                            Description = "ATM WITHDRAWAL 123 MAIN ST SAN FRANCISCO CA",
                            Type = 1
                        },
                        new
                        {
                            Id = 10,
                            Amount = 125.50m,
                            Balance = "$6,905.32",
                            Date = "2019-11-25",
                            Description = "DIVIDEND REINVESTMENT PLAN",
                            Type = 0
                        },
                        new
                        {
                            Id = 11,
                            Amount = 63.18m,
                            Balance = "$6,779.82",
                            Date = "2019-11-24",
                            Description = "TRADER JOE'S #455 SAN FRANCISCO CA",
                            Type = 1
                        },
                        new
                        {
                            Id = 12,
                            Amount = 9.99m,
                            Balance = "$6,843.00",
                            Date = "2019-11-22",
                            Description = "APPLE.COM/BILL CUPERTINO CA",
                            Type = 1
                        },
                        new
                        {
                            Id = 13,
                            Amount = 18.50m,
                            Balance = "$6,852.99",
                            Date = "2019-11-21",
                            Description = "UBER *TRIP HELP.UBER.COM CA",
                            Type = 1
                        },
                        new
                        {
                            Id = 14,
                            Amount = 3.45m,
                            Balance = "$6,871.49",
                            Date = "2019-11-20",
                            Description = "INTEREST CREDIT HACKERBANK CHECKING",
                            Type = 0
                        },
                        new
                        {
                            Id = 15,
                            Amount = 89.99m,
                            Balance = "$6,868.04",
                            Date = "2019-11-19",
                            Description = "COMCAST XFINITY DES:AUTOPAY ID: 4482991",
                            Type = 1
                        },
                        new
                        {
                            Id = 16,
                            Amount = 134.22m,
                            Balance = "$6,958.03",
                            Date = "2019-11-18",
                            Description = "PG&E DES:ELECTRIC ID: 5839201",
                            Type = 1
                        },
                        new
                        {
                            Id = 17,
                            Amount = 3500.00m,
                            Balance = "$7,092.25",
                            Date = "2019-11-15",
                            Description = "PAYROLL DIRECT DEPOSIT TECHCORP INC",
                            Type = 0
                        },
                        new
                        {
                            Id = 18,
                            Amount = 450.00m,
                            Balance = "$3,592.25",
                            Date = "2019-11-14",
                            Description = "ZELLE TRANSFER FROM MIKE J.",
                            Type = 0
                        },
                        new
                        {
                            Id = 19,
                            Amount = 47.83m,
                            Balance = "$3,142.25",
                            Date = "2019-11-13",
                            Description = "SAFEWAY #1234 SAN FRANCISCO CA",
                            Type = 1
                        },
                        new
                        {
                            Id = 20,
                            Amount = 22.16m,
                            Balance = "$3,190.08",
                            Date = "2019-11-12",
                            Description = "WALGREENS #9876 SAN FRANCISCO CA",
                            Type = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
